"""
  This file provides all error codes for the program.
"""

ERR_OK = 0
WARN_OK = 0
ERR_MISSING_ARGUMENT = 100
ERR_MISMATCHED_FORMAT = 101
ERR_MISMATCHED_PLATFORM = 102
ERR_UNKNOWN_PLATFORM = 103
ERR_MISMATCHED_ARGUMENT = 104
ERR_UNKNOWN_ARGUMENT = 105

WARN_IMPLICIT_FORMAT = 200
WARN_MODULE_NOT_FOUND = 201
WARN_MOD_NOT_FOUND = 202
WARN_KEY_NOT_FOUND = 203
WARN_MAPPING_NOT_FOUND = 204
WARN_CORRUPTED_MAPPING = 205
WARN_DUPLICATED_FILE = 206
WARN_UNKNOWN_MOD_FILE = 207

WARN_BROKEN_MODULE = 250
WARN_UNKNOWN_MODULE = 251
WARN_LOOP_COLLECTION = 252
WARN_DEPRECATED_MODULE_TYPE = 253
